### PR TITLE
Make the extension usable again and use https

### PR DESCRIPTION
**Pull request by LennartRoeder**
Hi,
I found your little extension, but it was not working. Since the code was very minimal, I went ahead and fixed it.
I tested it it Chrome. I tried to find out, how to get the extension into Firefox, but after like 15 Minutes I gave up. Someone please test it and maybe tell me, hot to start non packaged extensions in FF. Since the change is not very big it will most likely work in FF, but who knows.

Greetings
Lennart

### CODE REVIEW

**Comment by Gitoffthelawn** [comment]
@thinking-aloud In the Firefox Developer Edition, you can install whatever you like.  Just zip it up and change the extension to xpi.  Then you will be able to easily install it and test it.  Hope that helps!

**Comment by LennartRoeder** [comment]
That did not work.
It says corrupt add-on.
I think it is because the grunt build is failing to setup the ff Add-On correctly, so I created an issue for it (https://github.com/joscha/prime-ratings/issues/3).
I am not interested in fixing that though. I wanted to fix the Chrome version and since it was easy, I did it with the Firefox version as well. I don't want to get into the details of FF Add-On creation, to test 2 lines of code which will most likely work.

**Comment by joscha** [comment]
Published as `0.0.5` for Chrome, should not take longer than 30 min to become available here: https://chrome.google.com/webstore/detail/pfnkplljjpbbbclllghfeakdlfcldpfj

**Comment by joscha** [comment]
thanks for the fix @thinking-aloud !

**Comment by LennartRoeder** [comment]
you are welcome. I'm glad, there is a working chrome extension again.

**Pull request merged**
